RacksDB web app
rackslab/RacksDB pull request #32
Opened 2023-11-03 11:16 UTC by florianLSP

fix #7

2023-11-09 11:25 UTC, rezib requested changes
Please fix following errors reported by `eslint`:

```
$ npm run lint

> ui@0.0.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore


/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/postcss.config.js
  1:1  error  'module' is not defined  no-undef

/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/tailwind.config.js
  2:1  error  'module' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)
```

Also please reformat your code with _prettier_ for more consistency:

```
$ npm run format
```

And fix the following _type-check_ error:

```
$ npm run type-check

> ui@0.0.0 type-check
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

src/components/InfrastructureContentCard.vue:62:157 - error TS2345: Argument of type 'string' is not assignable to parameter of type '"nodes" | "storage" | "network"'.

62                         <span class="text-base font-normal leading-tight  dark:text-gray-400 capitalize text-purple-700 cursor-pointer" @click="popUp(name, equipment)">{{ id }}</span>
                                                                                                                                                               ~~~~~~~~~


Found 1 error in src/components/InfrastructureContentCard.vue:62
```

Please also add mention to copyright and license in SPDX format in all source code files header.

Also please add newline at the end of your files. For the record, this can de done automatically in VSCode with `files.insertFinalNewline: true` setting.

Some methods (ex: `getDatacenters()`) are duplicated in multiple views and components. I think you should introduce a composable to define all interfaces/types (Datacenter, Room, Infrastructures, etc) with all methods to request the API. Then all views and components could use this composable to import types/interfaces and request the API.

Have you tested the UI with multiple datacenters, multiple rooms in a datacenter and multiple infrastructures? We could work together on the definition of such an example database if needed.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterDetailsView.vue
> +            <tbody v-for="room in datacenterDetails?.rooms" :key="room.name">
I the whole table should not be be display while datacenterDetails is undefined, instead of relying on optional chaining operator for its body.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterDetailsView.vue
> +                        <router-link :to="{name: 'datacenterroom', params: {name: datacenterDetails?.name, datacenterRoom: room.name}}">
You can probably just use _name_ prop instead of `datacenterDetails.name` here.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterRoomView.vue
> +    name: String,
_name_ is the name of what? The variable name is not clear in this case.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterRoomView.vue
> +function listInfrastructures(){
Please add comment to explain what this function is supposed to do and what it returns.

Considering where this function is called, you want to list all infrastructures in a specific rack. Currently, it returns the infrastructure of the first node in the first rack. The for loop is not even used as it returns on the 1st iteration. It must be fixed.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterRoomView.vue
> +        <img :src="`${inject(injectionKey)!.api_server}/draw/room/${ props.datacenterRoom }.svg`" alt="" @click="openImg()" class="h-screen max-w-full bg-white" >
The URL of the image is used twice, it should be returned by a function to avoid duplication.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterRoomView.vue
> +function openImg(){
This function is also used to close image modal. A better name would be `toggleImageModal()`.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/InfrastructureDetailsView.vue
> +function openImg(){
As well as for `DatacenterRoomView`, this function is also used to close image modal. A better name would be `toggleImageModal()`.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/InfrastructureDetailsView.vue
> +function choseView(){
Please add comment to explain what this function does.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/InfrastructureDetailsView.vue
> +function rackDetails(rackName: string){
Please add comment to explain what this function does.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/InfrastructureDetailsView.vue
> +    <div v-show="tableView" class="pb-10">
Cards are in a component and the table is not. Please create an infrastructure table component to be consistent for both ways of representing the data.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/InfrastructureDetailsView.vue
> +    <img :src="`${inject(injectionKey)!.api_server}/draw/infrastructure/${ props.name }.svg`" alt="" @click="openImg()" class="h-96 max-w-500 mx-auto p-10">
As well as for `DatacenterRoomView`, the URL of the image is used twice, it should be returned by a function to avoid duplication.

2023-11-09 11:25 UTC, rezib commented on racksdb/web/ui/src/views/InfrastructureDetailsView.vue
> +        <InfrastructureCards v-if="infrastructureDetails" :infrastructure="infrastructureDetails" searchItem="nodes" />
`<InfrastructureCards/>` is called three times for nodes, storage and network and the component checks whether it is called for nodes, storage and network to display only the correct searched item. Why don't you just call it once and let it display all nodes, storage and network?

2023-11-13 10:00 UTC, florianLSP commented on racksdb/web/ui/public/assets/table.svg
link of the website where i found the icons : https://fonts.google.com/icons

2023-11-13 11:16 UTC, rezib commented on racksdb/web/ui/public/assets/table.svg
OK, I think a better option is to use [dedicated NPM package](https://github.com/marella/material-design-icons/tree/main/svg#readme) rather than bundling the icons.

2023-11-14 08:47 UTC, florianLSP commented on racksdb/web/ui/public/assets/racks_black.jpg
The license of this file is under the "Creative Commons" and it comes from "Wikimedia Commons"
Since we don't have the same license i can't use it so I'm going to delete it.

2023-12-06 09:13 UTC, rezib commented on racksdb/web/ui/src/views/DatacenterRoomView.vue
> +  <img
To display room and infrastructure images, you will need to request RacksDB API with Axios and POST method. You will probably need to specify that the type of the response data is a blob. Then you will be able to create a fictional URL with `URL.URL.createObjectURL(blob)` and use this generated URL in `src` attribute of `<img />` tag.

2023-12-13 10:19 UTC, rezib approved these changes

2023-12-13 11:10 UTC, rezib requested changes
Please fix this:

```console
$ npm run lint

> racksdb-webui@0.2.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore


Oops! Something went wrong! :(

ESLint: 8.50.0

Error: Cannot read .eslintignore file: /home/remi/Documents/git/products/RacksDB/racksdb/web/ui/.gitignore
Error: ENOENT: no such file or directory, open '/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/.gitignore'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at readFile (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2491:35)
    at loadESLintIgnoreFile (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2619:16)
    at ConfigArrayFactory.loadESLintIgnore (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2925:32)
    at createCLIConfigArray (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3643:34)
    at new CascadingConfigArrayFactory (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3724:29)
    at new CLIEngine (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/eslint/lib/cli-engine/cli-engine.js:617:36)
    at new ESLint (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/eslint/lib/eslint/eslint.js:430:27)
    at Object.execute (/home/remi/Documents/git/products/RacksDB/racksdb/web/ui/node_modules/eslint/lib/cli.js:382:24)
```

Also please re-run `npm run format`.

Please ensure new line is present at the end of all files.

2023-12-22 14:22 UTC, rezib approved these changes

2023-12-22 14:33 UTC, merged